### PR TITLE
Issue #1: Adds postgresql support and switch to agnostic version

### LINKED ISSUE #1: PostreSQL support
Hello guys. Could you add support PostgreSQL driver for Adminer. Now I don't have possibility t choose from select list another option than MySQL.

Thanks.

### PR DESCRIPTION
**Pull request by mradcliffe**
Resolves #1 .

I changed the adminer release to the -en.php one instead of mysql-en.php. I'm not sure what side effect that will cause.

### CODE REVIEW

**Comment by mradcliffe** [comment]
Getting some random errors when viewing actual data. It might be an issue with adminer itself.

```
Warning: strlen() expects parameter 1 to be string, resource given in /var/www/html/adminer.php on line 1517
```

**Comment by csandanov** [comment]
What version of postgres are you using when receiving this error?

**Comment by mradcliffe** [comment]
I'm using the `wodby/postgres:9.6-1.1.0` image.

**Comment by csandanov** [comment]
We should figure out where this error comes from, maybe inconsistency with php 7.1 or something. And I guess we should have pgadmin image

**Comment by mradcliffe** [comment]
I wasn't able to look into this today, which is usually the day I can do things. Spent too much time on other things. Might have some more time this weekend.

**Comment by mradcliffe** [comment]
I looked at it a bit closer, but it's very difficult to debug adminer since the container has it as some sort of compiled php file.

* The column value is being displayed so adminer is "working" practically.
* Example tables/columns that this happens on:
    * **router.fit** which is an integer column not in the index, not a unique key, but has a default value of 0.
    * **key_value.name** which is a varchar column in the primary key index.
    * **menu_tree.route_param_key** which is a varchar column not null, not in any indexes or primary/unique key. The url, title columns are different types of columns as well.

I can't find any pattern as to why. I'll probably file a bug upstream next.

**Comment by csandanov** [comment]
Implemented in https://github.com/wodby/adminer/releases/tag/3.0.0

**Pull request closed without merging**
